# Generated by Django 4.2 on 2023-04-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctionitem',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='Title')),
                ('artist', models.TextField(db_column='Artist')),
                ('genre', models.TextField(db_column='Genre')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'AuctionItem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auctionid', models.AutoField(db_column='AuctionID', primary_key=True, serialize=False)),
                ('startdatetime', models.BinaryField(db_column='StartDateTime')),
                ('enddatetime', models.TextField(db_column='EndDateTime')),
                ('checkedbystaff', models.IntegerField(blank=True, db_column='CheckedByStaff', null=True)),
            ],
            options={
                'db_table': 'Auctions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('clientid', models.AutoField(db_column='ClientID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('address', models.TextField(db_column='Address')),
            ],
            options={
                'db_table': 'Clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('unitsdelivered', models.IntegerField(db_column='UnitsDelivered')),
                ('dateofdelivery', models.TextField(db_column='DateOfDelivery', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeeid', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('surname', models.TextField(db_column='Surname')),
                ('email', models.TextField(blank=True, db_column='Email', null=True)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registeredclients',
            fields=[
                ('username', models.TextField(db_column='Username', primary_key=True, serialize=False)),
                ('password', models.TextField(db_column='Password')),
                ('email', models.TextField(db_column='Email', unique=True)),
            ],
            options={
                'db_table': 'RegisteredClients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('saleid', models.AutoField(db_column='SaleID', primary_key=True, serialize=False)),
                ('dateoftransaction', models.TextField(db_column='DateOfTransaction')),
                ('vinylid', models.IntegerField(blank=True, db_column='VinylID', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'Sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vinyls',
            fields=[
                ('vinylid', models.AutoField(db_column='VinylID', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='Title')),
                ('artist', models.TextField(db_column='Artist')),
                ('genre', models.TextField(db_column='Genre')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Vinyls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workshopjobs',
            fields=[
                ('jobid', models.AutoField(db_column='JobID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('ordereddate', models.TextField(blank=True, db_column='OrderedDate', null=True)),
                ('completeddate', models.TextField(blank=True, db_column='CompletedDate', null=True)),
            ],
            options={
                'db_table': 'WorkshopJobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('username', models.OneToOneField(db_column='Username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='shop.registeredclients')),
                ('timestamp', models.TextField(db_column='Timestamp')),
                ('value', models.IntegerField(db_column='Value')),
            ],
            options={
                'db_table': 'Bids',
                'managed': False,
            },
        ),
    ]
